### ISSUE TITLE
Unable to build ui

### ISSUE THREAD

**Issue by mc-sunw** [Sharders/sharder-chain#66]
I did a clone of the repo and followed the build instructions but it fails building npm:

mark@mac-work[647]% npm run build

> SharderClient@1.0.0 build /Users/mark/git/github/sharder-chain/ui
> webpack --config build/webpack.prod.js

 95% emitting                                                                             
Starting to optimize CSS...
Processing src.70494ffb.css...
Processing vendor.8d9d541c.css...
Processed src.70494ffb.css, before: 233486, after: 207607, ratio: 88.92%
Processed vendor.8d9d541c.css, before: 7428, after: 2149, ratio: 28.93%
Hash: 3fa63ac59822652f7361
Version: webpack 2.4.1
Time: 29593ms
                                   Asset       Size  Chunks                    Chunk Names
    732389ded34cb9c52dd88271f1345af9.ttf      56 kB          [emitted]         
   535877f50039c0cb49a6196a5b7517cd.woff    28.2 kB          [emitted]         
    c63221d6d407a46ab16e761b97a7f24d.svg  955 bytes          [emitted]         
    0fcc24e91a25bab75220b7ccfc6fd5ce.svg  689 bytes          [emitted]         
    cbbb578ecbdca7b09b145a7b5a9d2969.svg  325 bytes          [emitted]         
    c2513be65b4779e23ab454a649c3960d.svg  342 bytes          [emitted]         
    739ceb2d6e8a0a7a05a014cd319c35e7.svg  292 bytes          [emitted]         
    d29b1a3adfb32009c62c3c0f3047b2d2.svg  720 bytes          [emitted]         
    b672ebeb4e7ddeb6e65033d4fee628e4.png  310 bytes          [emitted]         
    806e93713c22757acfc00a2529cdb635.png  247 bytes          [emitted]         
    df838ee4466293597d04ec1aeb2f6913.png  333 bytes          [emitted]         
    7f5c8718f317a65d8b2df375e350f6b8.svg  710 bytes          [emitted]         
    a68eed0eef91dd354044d099d35851eb.svg    1.07 kB          [emitted]         
    4a1bfc88b74d4b05694151b7c556712c.svg  322 bytes          [emitted]         
    c5fda73d7dd6134d21d38bba54a37055.svg  634 bytes          [emitted]         
    90b1ace35b6b9ed43d69b35c4629f8ec.svg    1.06 kB          [emitted]         
    e830a2432889db5954e56edffe2e34a3.svg  841 bytes          [emitted]         
    d502f6e7a901961981d6d57aefbdd59c.png    5.35 kB          [emitted]         
    074163b7a503673f4b3dffdc66a05840.png    2.35 kB          [emitted]         
    385ec04e5c88baabd95f52782e3e7e08.png    2.21 kB          [emitted]         
    39274c7e31834fa3c59b50cf8884dd49.png    41.2 kB          [emitted]         
    7b7c07a0419908f8f75af722228fcd29.png  251 bytes          [emitted]         
    76894d35b252344138a2de2a1927d9ca.svg  851 bytes          [emitted]         
    73e7e4dacbfff20a5f0337cd83612cdc.svg  826 bytes          [emitted]         
    88771ae84954f5733a3af160c5358693.svg     2.4 kB          [emitted]         
    687861f5c829bbe59d395153ee04efce.png    1.51 kB          [emitted]         
    dabf442dfa867a5cdb749bb5917a70b1.png    1.86 kB          [emitted]         
    07461a2dcfa5404f6b24945588ef532e.svg  227 bytes          [emitted]         
    9819f59cba9283d9ef94b785af000278.png    1.51 kB          [emitted]         
    54442ab9ae10187327c32e42b756c8a8.png    1.13 kB          [emitted]         
    4a30b3e55457bcd5715c10a6a5ae82df.png    4.41 kB          [emitted]         
    d20bc86fc58127ad23c9d88810b5e600.png    1.71 kB          [emitted]         
    fbf389fa7082787b2732a3cdda787e84.svg  530 bytes          [emitted]         
    044f9803e7ca25327fb1a04b589056e0.svg    1.03 kB          [emitted]         
    a358ff4477d1666ab6dbe6a7fae7f085.png  362 bytes          [emitted]         
    922a4efa115885482ce022eafbec0419.png    1.02 kB          [emitted]         
    213818bccbeb8e6fd6bfecffc1226df7.png  740 bytes          [emitted]         
    c358accb30502f4e34c86c78103e1a39.png  413 bytes          [emitted]         
    74bf157a89405dacc391c366a00370ba.png  471 bytes          [emitted]         
    079092795bd23c4c34e0bda34f48d505.png  583 bytes          [emitted]         
    1adbec9927fae92e80c08ec3f3f07498.svg  577 bytes          [emitted]         
    3727c1af399cd9267f570ccf7f0a4d2a.svg  448 bytes          [emitted]         
    eddede374aaea1b295954304b565951b.svg  524 bytes          [emitted]         
    8f7aaaaa3042e0b188913992630b28bd.svg  739 bytes          [emitted]         
    5331db74b8cb208e73a7049d6d26cf2c.svg  597 bytes          [emitted]         
    26e22b4be87e8d24beaf0b3d1371dbaa.svg  995 bytes          [emitted]         
    fdb800807de935941e627fecf78d953c.svg    1.42 kB          [emitted]         
    2ecbe72b6084097721a7f1039ead3d9a.png  814 bytes          [emitted]         
    e68e2562c3aa71b935713ba182c8cd18.png  664 bytes          [emitted]         
    d08bc1bada11565aacdaaa2beb5768a4.png  660 bytes          [emitted]         
    0c93540dfb70afb626f22b096515e92b.svg  528 bytes          [emitted]         
    dd362014e51ed1140f9778bef583c741.svg  777 bytes          [emitted]         
    00ff9e71960e02935d4249508994b75c.svg  260 bytes          [emitted]         
    a2e3c4b8c901a8bef2a6b843137474cf.png  200 bytes          [emitted]         
    a0d15f3b3bec6ce2adf0b0933b069d52.png  488 bytes          [emitted]         
    ffd25987ee4734663d37daefc73b017e.png    1.42 kB          [emitted]         
    a70e8f3ea79976cae37b00c9134c36f1.png  981 bytes          [emitted]         
    8939ec7ae8fce58ef770445f30e7ebfc.svg  804 bytes          [emitted]         
    94ed63df5a860b0abf5ee3979fcf9d07.png  808 bytes          [emitted]         
    4ddb7a491fac35251fe5fa3a7fe6e125.png    1.42 kB          [emitted]         
    2f581e1dd7588597d93b6fe3eb5d7a85.png    1.06 kB          [emitted]         
    f39acc57a1ecbec175bb358e51857f59.svg    3.81 kB          [emitted]         
                         src.acfe9dc1.js    3.51 MB       0  [emitted]  [big]  src
                      vendor.046c481a.js     852 kB       1  [emitted]  [big]  vendor
                        src.70494ffb.css     208 kB       0  [emitted]         src
                     vendor.8d9d541c.css    2.15 kB       1  [emitted]         vendor
                    src.70494ffb.css.map   82 bytes       0  [emitted]         src
                 vendor.8d9d541c.css.map  512 bytes       1  [emitted]         vendor
                              index.html  797 bytes          [emitted]         
            sso/img/background-login.svg    6.07 kB          [emitted]         
                        sso/js/cookie.js    1.82 kB          [emitted]         
                         sso/js/index.js    1.46 kB          [emitted]         
               sso/js/util/converters.js    9.12 kB          [emitted]         
              sso/js/util/curve25519_.js    37.1 kB          [emitted]         
               sso/js/util/curve25519.js    31.3 kB          [emitted]         
               sso/js/util/extensions.js    1.58 kB          [emitted]         
                   sso/js/util/locale.js    27.2 kB          [emitted]         
                     sso/js/util/pako.js     201 kB          [emitted]         
                sso/js/util/scaddress.js    8.38 kB          [emitted]         
        sso/js/util/sso.assetexchange.js    93.4 kB          [emitted]         
               sso/js/util/sso.blocks.js    14.2 kB          [emitted]         
              sso/js/util/sso.console.js    5.42 kB          [emitted]         
            sso/js/util/sso.constants.js    11.5 kB          [emitted]         
             sso/js/util/sso.contacts.js    16.1 kB          [emitted]         
           sso/js/util/sso.encryption.js    27.4 kB          [emitted]         
    sso/js/util/sso.feature.detection.js    7.92 kB          [emitted]         
                sso/js/util/sso.forms.js    23.5 kB          [emitted]         
                      sso/js/util/sso.js    85.2 kB          [emitted]         
         sso/js/util/sso.localstorage.js     6.8 kB          [emitted]         
                sso/js/util/sso.login.js    29.3 kB          [emitted]         
sso/js/util/sso.modals.accountdetails.js    5.99 kB          [emitted]         
      sso/js/util/sso.modals.advanced.js    20.9 kB          [emitted]         
         sso/js/util/sso.modals.token.js     5.2 kB          [emitted]         
        sso/js/util/sso.notifications.js    8.93 kB          [emitted]         
               sso/js/util/sso.server.js    74.2 kB          [emitted]         
             sso/js/util/sso.settings.js    26.1 kB          [emitted]         
            sso/js/util/sso.sitebuild.js    9.97 kB          [emitted]         
         sso/js/util/sso.transactions.js    42.9 kB          [emitted]         
                 sso/js/util/sso.util.js      56 kB          [emitted]         
                                .gitkeep    0 bytes          [emitted]         
        img/sharder-icon-def-128x128.png    5.05 kB          [emitted]         
          img/sharder-icon-def-32x32.png    1.44 kB          [emitted]         
          img/sharder-icon-def-64x64.png    2.33 kB          [emitted]         
           img/tray-icon-mac-320x320.png    8.33 kB          [emitted]         
                             favicon.ico    67.6 kB          [emitted]         
             img/tray-icon-def-64x64.png    2.33 kB          [emitted]         
                   sso/js/util/sha256.js    9.41 kB          [emitted]         
                                   sw.js    20.6 kB          [emitted]         
  [11] (webpack)/buildin/global.js 509 bytes {1} [built]
  [23] ./~/vue/dist/vue.esm.js 326 kB {1} [built]
  [44] ./~/element-ui/lib/utils/util.js 7.32 kB {1} [built]
 [211] ./~/element-ui/lib/element-ui.common.js 1.15 MB {1} [built]
 [212] ./~/normalize.css/normalize.css 41 bytes {1} [built]
 [213] ./~/material-design-icons/index.js 48 bytes {1} [built]
 [214] ./~/offline-plugin/runtime.js 4.44 kB {1} [built]
 [215] ./~/vue-router/dist/vue-router.esm.js 65.6 kB {1} [built]
 [216] ./~/vuex-router-sync/index.js 1.73 kB {1} [built]
 [217] ./~/vuex/dist/vuex.esm.js 26.1 kB {1} [built]
 [218] ./~/whatwg-fetch/fetch.js 13 kB {1} [built]
 [361] ./src/app.js 5.58 kB {0} [built]
 [362] ./src/pwa.js 578 bytes {0} [built]
 [442] ./src/index.js 241 bytes {0} [built]
[1092] multi vue vuex vue-router vuex-router-sync whatwg-fetch normalize.css offline-plugin/runtime element-ui material-design-icons 124 bytes {1} [built]
    + 1085 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets: 
  src.acfe9dc1.js (3.51 MB)
  vendor.046c481a.js (852 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  src (4.57 MB)
      vendor.046c481a.js
      vendor.8d9d541c.css
      src.acfe9dc1.js
      src.70494ffb.css
  vendor (854 kB)
      vendor.046c481a.js
      vendor.8d9d541c.css

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

ERROR in ./src/app.js
Module not found: Error: Can't resolve 'theme/index.css' in '/Users/mark/git/github/sharder-chain/ui/src'
 @ ./src/app.js 36:0-26
 @ ./src/index.js

ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./src/styles/css/index.scss
Module not found: Error: Can't resolve '../../../theme/fonts/element-icons.ttf' in '/Users/mark/git/github/sharder-chain/ui/src/styles/css'
 @ ./~/css-loader!./~/sass-loader/lib/loader.js!./src/styles/css/index.scss 7:235-284
 @ ./src/styles/css/index.scss
 @ ./src/app.js
 @ ./src/index.js

ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./src/styles/css/index.scss
Module not found: Error: Can't resolve '../../../theme/fonts/element-icons.woff' in '/Users/mark/git/github/sharder-chain/ui/src/styles/css'
 @ ./~/css-loader!./~/sass-loader/lib/loader.js!./src/styles/css/index.scss 7:145-195
 @ ./src/styles/css/index.scss
 @ ./src/app.js
 @ ./src/index.js

ERROR in ./src/styles/css/index.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '../../../theme/fonts/element-icons.woff' in '/Users/mark/git/github/sharder-chain/ui/src/styles/css'
    at factoryCallback (/Users/mark/git/github/sharder-chain/ui/node_modules/webpack/lib/Compilation.js:260:39)
    at /Users/mark/git/github/sharder-chain/ui/node_modules/webpack/lib/NormalModuleFactory.js:247:20
    at /Users/mark/git/github/sharder-chain/ui/node_modules/webpack/lib/NormalModuleFactory.js:65:21
    at /Users/mark/git/github/sharder-chain/ui/node_modules/webpack/lib/NormalModuleFactory.js:138:21
    at /Users/mark/git/github/sharder-chain/ui/node_modules/async/dist/async.js:3888:9
    at /Users/mark/git/github/sharder-chain/ui/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/mark/git/github/sharder-chain/ui/node_modules/async/dist/async.js:1062:13)
    at /Users/mark/git/github/sharder-chain/ui/node_modules/async/dist/async.js:969:16
    at /Users/mark/git/github/sharder-chain/ui/node_modules/async/dist/async.js:3885:13
    at /Users/mark/git/github/sharder-chain/ui/node_modules/webpack/lib/NormalModuleFactory.js:130:23
    at onError (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/mark/git/github/sharder-chain/ui/node_modules/tapable/lib/Tapable.js:252:11)
    at /Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/mark/git/github/sharder-chain/ui/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/mark/git/github/sharder-chain/ui/node_modules/tapable/lib/Tapable.js:249:35)
    at /Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/Resolver.js:168:10)
    at loggingCallbackWrapper (/Users/mark/git/github/sharder-chain/ui/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/mark/git/github/sharder-chain/ui/node_modules/tapable/lib/Tapable.js:252:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! SharderClient@1.0.0 build: `webpack --config build/webpack.prod.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the SharderClient@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ben-xy** [comment]
before run build you should install the theme 'npm run generate_theme'

**Comment by mc-sunw** [comment]
Ok, tried that:

mark@mac-work[653]% npm run generate_theme

> SharderClient@1.0.0 generate_theme /Users/mark/git/github/sharder-chain/ui
> et -c ./src/styles/element-variables.css

fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/Users/mark/git/github/sharder-chain/ui/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/mark/git/github/sharder-chain/ui/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/mark/git/github/sharder-chain/ui/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SharderClient@1.0.0 generate_theme: `et -c ./src/styles/element-variables.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the SharderClient@1.0.0 generate_theme script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ben-xy** [comment]
delete the 'ui/node_modules' folder -> npm i  -> npm run generate_theme -> npm run dev/build

**Comment by ben-xy** [comment]
Please check your compilation environment if you can’t finish the compilation. We can compile the ui module with: npm v6.4.1 & node v11.9.0

**Comment by mc-sunw** [comment]
Yeah, it was the versions that were important.
